import {Coach} from './models/coach.model';
import {Player} from './models/player.model';
import {BasketballEvent} from './models/event.model';


export const COACH: Coach = {
    firstName: 'Sjon', surname: 'de Trainer'
};

export const BASKETBALLEVENTS: BasketballEvent[] = [
    {
        location: 'Sporthal Diemen', players: [
        {age: 12, balance: 89, firstName: 'Justin', gender: 'male', id: 7, present: false, surname: 'Lier'},
        {age: 8, balance: -27, firstName: 'Mirjam', gender: 'female', id: 9, present: false, surname: 'Bakker'},
        {age: 8, balance: 191, firstName: 'Leon', gender: 'male', id: 15, present: false, surname: 'Aalst'},
        {age: 9, balance: 189, firstName: 'Isa', gender: 'female', id: 18, present: false, surname: 'Weert'},
        {age: 14, balance: 162, firstName: 'Michael', gender: 'male', id: 27, present: false, surname: 'Zanden'},
        {age: 6, balance: 99, firstName: 'Tim', gender: 'male', id: 29, present: true, surname: 'Uden'},
        {age: 9, balance: 115, firstName: 'Kim', gender: 'female', id: 38, present: false, surname: 'Zandbergen'},
    ],
        timestamp: 1556784000000
    },
    {
        location: 'Alderman Verheij sporthal', players: [
        {age: 8, balance: -7, firstName: 'Eva', gender: 'female', id: 3, present: true, surname: 'Lier'},
        {age: 6, balance: -15, firstName: 'Tessa', gender: 'female', id: 6, present: false, surname: 'Cremers'},
        {age: 4, balance: 104, firstName: 'Merijn', gender: 'male', id: 24, present: true, surname: 'Maanen'},
        {age: 15, balance: 24, firstName: 'Leon', gender: 'male', id: 28, present: true, surname: 'Bouwhuis'},
        {age: 10, balance: -44, firstName: 'Tim', gender: 'male', id: 35, present: true, surname: 'Cremers'},
        {age: 11, balance: 99, firstName: 'Aaron', gender: 'male', id: 41, present: true, surname: 'Klok'},
        {age: 6, balance: 30, firstName: 'Natasha', gender: 'female', id: 46, present: false, surname: 'Krol'},
        {age: 9, balance: 189, firstName: 'Emma', gender: 'female', id: 47, present: true, surname: 'Bogaard'},
        {age: 14, balance: -39, firstName: 'Lorenzo', gender: 'male', id: 48, present: true, surname: 'Altena'},
        {age: 16, balance: -11, firstName: 'Eva', gender: 'female', id: 54, present: false, surname: 'Jonkman'},
        {age: 10, balance: -10, firstName: 'Tijmen', gender: 'male', id: 55, present: false, surname: 'Claassen'},
        {age: 8, balance: 177, firstName: 'Robin', gender: 'male', id: 57, present: true, surname: 'Koelewijn'},
        {age: 16, balance: 141, firstName: 'Jimmy', gender: 'male', id: 58, present: true, surname: 'Olde'},
        {age: 12, balance: 151, firstName: 'Eva', gender: 'female', id: 60, present: true, surname: 'Bogaard'},
        {age: 8, balance: 95, firstName: 'Giovanni', gender: 'male', id: 61, present: false, surname: 'Westerhof'},
        {age: 7, balance: -45, firstName: 'Sharon', gender: 'female', id: 66, present: true, surname: 'Nijkamp'},
        {age: 6, balance: 39, firstName: 'Tessa', gender: 'female', id: 69, present: false, surname: 'Klein'},
        {age: 8, balance: 34, firstName: 'Sander', gender: 'male', id: 71, present: false, surname: 'Kleef'},
        {age: 13, balance: 134, firstName: 'Marco', gender: 'male', id: 74, present: true, surname: 'Overbeek'},
        {age: 8, balance: 104, firstName: 'Richard', gender: 'male', id: 76, present: true, surname: 'Zwiers'},
        {age: 13, balance: 87, firstName: 'Sara', gender: 'female', id: 79, present: true, surname: 'Lier'},
    ],
        timestamp: 1556798400000
    },
    {
        location: 'Sporthal Zeeburg', players: [
        {age: 14, balance: 99, firstName: 'Isabel', gender: 'female', id: 4, present: false, surname: 'Verkerk'},
        {age: 5, balance: -21, firstName: 'Tessa', gender: 'female', id: 8, present: false, surname: 'Loos'},
        {age: 5, balance: 60, firstName: 'Fleur', gender: 'female', id: 10, present: false, surname: 'Bleeker'},
        {age: 12, balance: 55, firstName: 'Denise', gender: 'female', id: 12, present: false, surname: 'Smit'},
        {age: 5, balance: 131, firstName: 'Britt', gender: 'female', id: 14, present: false, surname: 'Wever'},
        {age: 4, balance: -9, firstName: 'Calvin', gender: 'male', id: 19, present: false, surname: 'Knaap'},
        {age: 12, balance: 50, firstName: 'Ezra', gender: 'male', id: 22, present: true, surname: 'Verschuren'},
        {age: 12, balance: 123, firstName: 'Julia', gender: 'female', id: 31, present: true, surname: 'Loos'},
        {age: 6, balance: 169, firstName: 'Faruk', gender: 'male', id: 56, present: true, surname: 'Verstappen'},
        {age: 4, balance: 104, firstName: 'Emily', gender: 'female', id: 68, present: false, surname: 'Nijhof'},
        {age: 14, balance: 70, firstName: 'Sander', gender: 'male', id: 72, present: false, surname: 'Snoek'},
        {age: 16, balance: -22, firstName: 'Romy', gender: 'female', id: 78, present: true, surname: 'Broeders'},
    ],
        timestamp: 1556812800000
    },
    {
        location: 'Sporthal Oostenburg', players: [
        {age: 14, balance: 98, firstName: 'Marielle', gender: 'female', id: 2, present: true, surname: 'Zuidema'},
        {age: 8, balance: 161, firstName: 'Robert', gender: 'male', id: 13, present: false, surname: 'Wind'},
        {age: 16, balance: 96, firstName: 'Lars', gender: 'male', id: 21, present: true, surname: 'Overbeek'},
        {age: 13, balance: 48, firstName: 'Robin', gender: 'male', id: 25, present: true, surname: 'Cremers'},
        {age: 16, balance: 123, firstName: 'David', gender: 'male', id: 30, present: false, surname: 'Olde'},
        {age: 9, balance: 50, firstName: 'Bas', gender: 'male', id: 32, present: false, surname: 'Maassen'},
        {age: 11, balance: 13, firstName: 'Bram', gender: 'male', id: 37, present: false, surname: 'Kock'},
        {age: 11, balance: 82, firstName: 'Thom', gender: 'male', id: 45, present: false, surname: 'Veenendaal'},
        {age: 10, balance: 75, firstName: 'Jolle', gender: 'female', id: 49, present: true, surname: 'Akkerman'},
        {age: 8, balance: 30, firstName: 'Julie', gender: 'female', id: 50, present: false, surname: 'Ooms'},
        {age: 3, balance: 83, firstName: 'Marcel', gender: 'male', id: 51, present: true, surname: 'Bloem'},
        {age: 9, balance: -4, firstName: 'Myrthe', gender: 'female', id: 52, present: true, surname: 'Buuren'},
        {age: 14, balance: 186, firstName: 'Tijmen', gender: 'male', id: 62, present: false, surname: 'Zandbergen'},
        {age: 15, balance: 28, firstName: 'Linde', gender: 'female', id: 64, present: false, surname: 'Broeders'},
        {age: 3, balance: 25, firstName: 'Faruk', gender: 'male', id: 70, present: true, surname: 'Verschuren'},
        {age: 6, balance: -35, firstName: 'Robbert', gender: 'male', id: 75, present: true, surname: 'Otter'},
        {age: 3, balance: 197, firstName: 'Leon', gender: 'male', id: 80, present: true, surname: 'Knaap'},
    ],
        timestamp: 1556874000000
    },
    {
        location: 'Sporthallen Zuid', players: [
        {age: 12, balance: -47, firstName: 'Martijn', gender: 'male', id: 1, present: false, surname: 'Westerhof'},
        {age: 8, balance: 141, firstName: 'Stijn', gender: 'male', id: 11, present: true, surname: 'Wassink'},
        {age: 11, balance: 163, firstName: 'Rosalie', gender: 'female', id: 16, present: false, surname: 'Gent'},
        {age: 5, balance: 155, firstName: 'Robert', gender: 'male', id: 17, present: false, surname: 'Kroeze'},
        {age: 7, balance: -44, firstName: 'Joris', gender: 'male', id: 20, present: true, surname: 'Hoog'},
        {age: 13, balance: 153, firstName: 'Rosalie', gender: 'female', id: 23, present: true, surname: 'Klok'},
        {age: 3, balance: 92, firstName: 'Jesse', gender: 'male', id: 34, present: false, surname: 'Vossen'},
        {age: 14, balance: 169, firstName: 'Danille', gender: 'female', id: 36, present: false, surname: 'Wijnands'},
        {age: 9, balance: 60, firstName: 'Anouk', gender: 'female', id: 40, present: true, surname: 'Kooten'},
        {age: 16, balance: 0, firstName: 'Vivian', gender: 'female', id: 42, present: true, surname: 'Nijkamp'},
        {age: 10, balance: -41, firstName: 'Marit', gender: 'female', id: 59, present: true, surname: 'Wassink'},
        {age: 9, balance: 34, firstName: 'Robbert', gender: 'male', id: 63, present: true, surname: 'Nijkamp'},
        {age: 4, balance: 61, firstName: 'Job', gender: 'male', id: 67, present: false, surname: 'Klijn'},
        {age: 13, balance: 84, firstName: 'Romy', gender: 'female', id: 73, present: true, surname: 'Wolff'},
        {age: 8, balance: 31, firstName: 'Hannah', gender: 'female', id: 77, present: false, surname: 'Klok'},
    ],
        timestamp: 1556888400000
    },
    {
        location: 'Sportcentrum Universum', players: [
        {age: 11, balance: 64, firstName: 'Martijn', gender: 'male', id: 5, present: true, surname: 'Cremers'},
        {age: 9, balance: 161, firstName: 'Tessa', gender: 'female', id: 26, present: false, surname: 'Braam'},
        {age: 3, balance: 45, firstName: 'Amy', gender: 'female', id: 33, present: false, surname: 'Wijnands'},
        {age: 10, balance: -23, firstName: 'Tessa', gender: 'female', id: 39, present: false, surname: 'Altena'},
        {age: 9, balance: 92, firstName: 'Benjamin', gender: 'male', id: 43, present: false, surname: 'Linders'},
        {age: 12, balance: 183, firstName: 'Britt', gender: 'female', id: 44, present: true, surname: 'Delft'},
        {age: 15, balance: -21, firstName: 'Jesse', gender: 'male', id: 53, present: true, surname: 'Braam'},
        {age: 14, balance: -33, firstName: 'Oussama', gender: 'male', id: 65, present: true, surname: 'Klein'},
    ],
        timestamp: 1556902800000
    },
    {
        location: 'Sporthal Diemen', players: [
        {age: 8, balance: -7, firstName: 'Eva', gender: 'female', id: 3, present: true, surname: 'Lier'},
        {age: 6, balance: -15, firstName: 'Tessa', gender: 'female', id: 6, present: false, surname: 'Cremers'},
        {age: 5, balance: 60, firstName: 'Fleur', gender: 'female', id: 10, present: false, surname: 'Bleeker'},
        {age: 12, balance: 55, firstName: 'Denise', gender: 'female', id: 12, present: false, surname: 'Smit'},
        {age: 8, balance: 161, firstName: 'Robert', gender: 'male', id: 13, present: false, surname: 'Wind'},
        {age: 9, balance: 189, firstName: 'Isa', gender: 'female', id: 18, present: false, surname: 'Weert'},
        {age: 4, balance: -9, firstName: 'Calvin', gender: 'male', id: 19, present: false, surname: 'Knaap'},
        {age: 13, balance: 48, firstName: 'Robin', gender: 'male', id: 25, present: true, surname: 'Cremers'},
        {age: 6, balance: 99, firstName: 'Tim', gender: 'male', id: 29, present: true, surname: 'Uden'},
        {age: 16, balance: 123, firstName: 'David', gender: 'male', id: 30, present: false, surname: 'Olde'},
        {age: 14, balance: -39, firstName: 'Lorenzo', gender: 'male', id: 48, present: true, surname: 'Altena'},
        {age: 3, balance: 83, firstName: 'Marcel', gender: 'male', id: 51, present: true, surname: 'Bloem'},
        {age: 15, balance: -21, firstName: 'Jesse', gender: 'male', id: 53, present: true, surname: 'Braam'},
        {age: 6, balance: 169, firstName: 'Faruk', gender: 'male', id: 56, present: true, surname: 'Verstappen'},
        {age: 14, balance: -33, firstName: 'Oussama', gender: 'male', id: 65, present: true, surname: 'Klein'},
        {age: 13, balance: 84, firstName: 'Romy', gender: 'female', id: 73, present: true, surname: 'Wolff'},
        {age: 16, balance: -22, firstName: 'Romy', gender: 'female', id: 78, present: true, surname: 'Broeders'},
    ],
        timestamp: 1557129600000
    },
    {
        location: 'Alderman Verheij sporthal', players: [
        {age: 14, balance: 98, firstName: 'Marielle', gender: 'female', id: 2, present: true, surname: 'Zuidema'},
        {age: 12, balance: 89, firstName: 'Justin', gender: 'male', id: 7, present: false, surname: 'Lier'},
        {age: 5, balance: 131, firstName: 'Britt', gender: 'female', id: 14, present: false, surname: 'Wever'},
        {age: 16, balance: 96, firstName: 'Lars', gender: 'male', id: 21, present: true, surname: 'Overbeek'},
        {age: 3, balance: 92, firstName: 'Jesse', gender: 'male', id: 34, present: false, surname: 'Vossen'},
        {age: 11, balance: 13, firstName: 'Bram', gender: 'male', id: 37, present: false, surname: 'Kock'},
        {age: 9, balance: 60, firstName: 'Anouk', gender: 'female', id: 40, present: true, surname: 'Kooten'},
        {age: 11, balance: 99, firstName: 'Aaron', gender: 'male', id: 41, present: true, surname: 'Klok'},
        {age: 11, balance: 82, firstName: 'Thom', gender: 'male', id: 45, present: false, surname: 'Veenendaal'},
        {age: 9, balance: -4, firstName: 'Myrthe', gender: 'female', id: 52, present: true, surname: 'Buuren'},
        {age: 10, balance: -41, firstName: 'Marit', gender: 'female', id: 59, present: true, surname: 'Wassink'},
        {age: 8, balance: 95, firstName: 'Giovanni', gender: 'male', id: 61, present: false, surname: 'Westerhof'},
        {age: 4, balance: 61, firstName: 'Job', gender: 'male', id: 67, present: false, surname: 'Klijn'},
        {age: 6, balance: 39, firstName: 'Tessa', gender: 'female', id: 69, present: false, surname: 'Klein'},
        {age: 3, balance: 25, firstName: 'Faruk', gender: 'male', id: 70, present: true, surname: 'Verschuren'},
        {age: 14, balance: 70, firstName: 'Sander', gender: 'male', id: 72, present: false, surname: 'Snoek'},
        {age: 13, balance: 134, firstName: 'Marco', gender: 'male', id: 74, present: true, surname: 'Overbeek'},
        {age: 13, balance: 87, firstName: 'Sara', gender: 'female', id: 79, present: true, surname: 'Lier'},
    ],
        timestamp: 1557144000000
    },
    {
        location: 'Sporthal Zeeburg', players: [
        {age: 12, balance: -47, firstName: 'Martijn', gender: 'male', id: 1, present: false, surname: 'Westerhof'},
        {age: 14, balance: 99, firstName: 'Isabel', gender: 'female', id: 4, present: false, surname: 'Verkerk'},
        {age: 4, balance: 104, firstName: 'Merijn', gender: 'male', id: 24, present: true, surname: 'Maanen'},
        {age: 9, balance: 161, firstName: 'Tessa', gender: 'female', id: 26, present: false, surname: 'Braam'},
        {age: 15, balance: 24, firstName: 'Leon', gender: 'male', id: 28, present: true, surname: 'Bouwhuis'},
        {age: 9, balance: 115, firstName: 'Kim', gender: 'female', id: 38, present: false, surname: 'Zandbergen'},
        {age: 10, balance: -23, firstName: 'Tessa', gender: 'female', id: 39, present: false, surname: 'Altena'},
        {age: 8, balance: 177, firstName: 'Robin', gender: 'male', id: 57, present: true, surname: 'Koelewijn'},
        {age: 8, balance: 104, firstName: 'Richard', gender: 'male', id: 76, present: true, surname: 'Zwiers'},
        {age: 8, balance: 31, firstName: 'Hannah', gender: 'female', id: 77, present: false, surname: 'Klok'},
    ],
        timestamp: 1557158400000
    },
    {
        location: 'Sporthal Oostenburg', players: [
        {age: 11, balance: 64, firstName: 'Martijn', gender: 'male', id: 5, present: true, surname: 'Cremers'},
        {age: 5, balance: -21, firstName: 'Tessa', gender: 'female', id: 8, present: false, surname: 'Loos'},
        {age: 8, balance: -27, firstName: 'Mirjam', gender: 'female', id: 9, present: false, surname: 'Bakker'},
        {age: 8, balance: 141, firstName: 'Stijn', gender: 'male', id: 11, present: true, surname: 'Wassink'},
        {age: 5, balance: 155, firstName: 'Robert', gender: 'male', id: 17, present: false, surname: 'Kroeze'},
        {age: 13, balance: 153, firstName: 'Rosalie', gender: 'female', id: 23, present: true, surname: 'Klok'},
        {age: 9, balance: 50, firstName: 'Bas', gender: 'male', id: 32, present: false, surname: 'Maassen'},
        {age: 16, balance: 0, firstName: 'Vivian', gender: 'female', id: 42, present: true, surname: 'Nijkamp'},
        {age: 6, balance: 30, firstName: 'Natasha', gender: 'female', id: 46, present: false, surname: 'Krol'},
        {age: 9, balance: 189, firstName: 'Emma', gender: 'female', id: 47, present: true, surname: 'Bogaard'},
        {age: 16, balance: -11, firstName: 'Eva', gender: 'female', id: 54, present: false, surname: 'Jonkman'},
        {age: 9, balance: 34, firstName: 'Robbert', gender: 'male', id: 63, present: true, surname: 'Nijkamp'},
        {age: 7, balance: -45, firstName: 'Sharon', gender: 'female', id: 66, present: true, surname: 'Nijkamp'},
        {age: 6, balance: -35, firstName: 'Robbert', gender: 'male', id: 75, present: true, surname: 'Otter'},
        {age: 3, balance: 197, firstName: 'Leon', gender: 'male', id: 80, present: true, surname: 'Knaap'},
    ],
        timestamp: 1557219600000
    },
    {
        location: 'Sporthallen Zuid', players: [
        {age: 8, balance: 191, firstName: 'Leon', gender: 'male', id: 15, present: false, surname: 'Aalst'},
        {age: 7, balance: -44, firstName: 'Joris', gender: 'male', id: 20, present: true, surname: 'Hoog'},
        {age: 10, balance: -44, firstName: 'Tim', gender: 'male', id: 35, present: true, surname: 'Cremers'},
        {age: 14, balance: 169, firstName: 'Danille', gender: 'female', id: 36, present: false, surname: 'Wijnands'},
        {age: 8, balance: 30, firstName: 'Julie', gender: 'female', id: 50, present: false, surname: 'Ooms'},
        {age: 16, balance: 141, firstName: 'Jimmy', gender: 'male', id: 58, present: true, surname: 'Olde'},
        {age: 12, balance: 151, firstName: 'Eva', gender: 'female', id: 60, present: true, surname: 'Bogaard'},
        {age: 15, balance: 28, firstName: 'Linde', gender: 'female', id: 64, present: false, surname: 'Broeders'},
        {age: 8, balance: 34, firstName: 'Sander', gender: 'male', id: 71, present: false, surname: 'Kleef'},
    ],
        timestamp: 1557234000000
    },
    {
        location: 'Sportcentrum Universum', players: [
        {age: 11, balance: 163, firstName: 'Rosalie', gender: 'female', id: 16, present: false, surname: 'Gent'},
        {age: 12, balance: 50, firstName: 'Ezra', gender: 'male', id: 22, present: true, surname: 'Verschuren'},
        {age: 14, balance: 162, firstName: 'Michael', gender: 'male', id: 27, present: false, surname: 'Zanden'},
        {age: 12, balance: 123, firstName: 'Julia', gender: 'female', id: 31, present: true, surname: 'Loos'},
        {age: 3, balance: 45, firstName: 'Amy', gender: 'female', id: 33, present: false, surname: 'Wijnands'},
        {age: 9, balance: 92, firstName: 'Benjamin', gender: 'male', id: 43, present: false, surname: 'Linders'},
        {age: 12, balance: 183, firstName: 'Britt', gender: 'female', id: 44, present: true, surname: 'Delft'},
        {age: 10, balance: 75, firstName: 'Jolle', gender: 'female', id: 49, present: true, surname: 'Akkerman'},
        {age: 10, balance: -10, firstName: 'Tijmen', gender: 'male', id: 55, present: false, surname: 'Claassen'},
        {age: 14, balance: 186, firstName: 'Tijmen', gender: 'male', id: 62, present: false, surname: 'Zandbergen'},
        {age: 4, balance: 104, firstName: 'Emily', gender: 'female', id: 68, present: false, surname: 'Nijhof'},
    ],
        timestamp: 1557248400000
    },
    {
        location: 'Sporthal Diemen', players: [
        {age: 12, balance: -47, firstName: 'Martijn', gender: 'male', id: 1, present: false, surname: 'Westerhof'},
        {age: 8, balance: -7, firstName: 'Eva', gender: 'female', id: 3, present: true, surname: 'Lier'},
        {age: 5, balance: -21, firstName: 'Tessa', gender: 'female', id: 8, present: false, surname: 'Loos'},
        {age: 8, balance: -27, firstName: 'Mirjam', gender: 'female', id: 9, present: false, surname: 'Bakker'},
        {age: 8, balance: 141, firstName: 'Stijn', gender: 'male', id: 11, present: true, surname: 'Wassink'},
        {age: 5, balance: 155, firstName: 'Robert', gender: 'male', id: 17, present: false, surname: 'Kroeze'},
        {age: 9, balance: 189, firstName: 'Isa', gender: 'female', id: 18, present: false, surname: 'Weert'},
        {age: 4, balance: -9, firstName: 'Calvin', gender: 'male', id: 19, present: false, surname: 'Knaap'},
        {age: 13, balance: 48, firstName: 'Robin', gender: 'male', id: 25, present: true, surname: 'Cremers'},
        {age: 6, balance: 99, firstName: 'Tim', gender: 'male', id: 29, present: true, surname: 'Uden'},
        {age: 3, balance: 92, firstName: 'Jesse', gender: 'male', id: 34, present: false, surname: 'Vossen'},
        {age: 15, balance: -21, firstName: 'Jesse', gender: 'male', id: 53, present: true, surname: 'Braam'},
        {age: 16, balance: -11, firstName: 'Eva', gender: 'female', id: 54, present: false, surname: 'Jonkman'},
        {age: 9, balance: 34, firstName: 'Robbert', gender: 'male', id: 63, present: true, surname: 'Nijkamp'},
        {age: 8, balance: 31, firstName: 'Hannah', gender: 'female', id: 77, present: false, surname: 'Klok'},
    ],
        timestamp: 1557388800000
    },
    {
        location: 'Alderman Verheij sporthal', players: [
        {age: 12, balance: 55, firstName: 'Denise', gender: 'female', id: 12, present: false, surname: 'Smit'},
        {age: 8, balance: 161, firstName: 'Robert', gender: 'male', id: 13, present: false, surname: 'Wind'},
        {age: 9, balance: 161, firstName: 'Tessa', gender: 'female', id: 26, present: false, surname: 'Braam'},
        {age: 9, balance: 92, firstName: 'Benjamin', gender: 'male', id: 43, present: false, surname: 'Linders'},
        {age: 9, balance: -4, firstName: 'Myrthe', gender: 'female', id: 52, present: true, surname: 'Buuren'},
        {age: 6, balance: -35, firstName: 'Robbert', gender: 'male', id: 75, present: true, surname: 'Otter'},
        {age: 8, balance: 104, firstName: 'Richard', gender: 'male', id: 76, present: true, surname: 'Zwiers'},
        {age: 13, balance: 87, firstName: 'Sara', gender: 'female', id: 79, present: true, surname: 'Lier'},
        {age: 3, balance: 197, firstName: 'Leon', gender: 'male', id: 80, present: true, surname: 'Knaap'},
    ],
        timestamp: 1557403200000
    },
    {
        location: 'Sporthal Zeeburg', players: [
        {age: 6, balance: -15, firstName: 'Tessa', gender: 'female', id: 6, present: false, surname: 'Cremers'},
        {age: 8, balance: 191, firstName: 'Leon', gender: 'male', id: 15, present: false, surname: 'Aalst'},
        {age: 11, balance: 163, firstName: 'Rosalie', gender: 'female', id: 16, present: false, surname: 'Gent'},
        {age: 12, balance: 50, firstName: 'Ezra', gender: 'male', id: 22, present: true, surname: 'Verschuren'},
        {age: 15, balance: 24, firstName: 'Leon', gender: 'male', id: 28, present: true, surname: 'Bouwhuis'},
        {age: 16, balance: 123, firstName: 'David', gender: 'male', id: 30, present: false, surname: 'Olde'},
        {age: 3, balance: 45, firstName: 'Amy', gender: 'female', id: 33, present: false, surname: 'Wijnands'},
        {age: 10, balance: -44, firstName: 'Tim', gender: 'male', id: 35, present: true, surname: 'Cremers'},
        {age: 10, balance: -23, firstName: 'Tessa', gender: 'female', id: 39, present: false, surname: 'Altena'},
        {age: 11, balance: 99, firstName: 'Aaron', gender: 'male', id: 41, present: true, surname: 'Klok'},
        {age: 16, balance: 0, firstName: 'Vivian', gender: 'female', id: 42, present: true, surname: 'Nijkamp'},
        {age: 11, balance: 82, firstName: 'Thom', gender: 'male', id: 45, present: false, surname: 'Veenendaal'},
        {age: 10, balance: -41, firstName: 'Marit', gender: 'female', id: 59, present: true, surname: 'Wassink'},
        {age: 7, balance: -45, firstName: 'Sharon', gender: 'female', id: 66, present: true, surname: 'Nijkamp'},
        {age: 4, balance: 61, firstName: 'Job', gender: 'male', id: 67, present: false, surname: 'Klijn'},
        {age: 4, balance: 104, firstName: 'Emily', gender: 'female', id: 68, present: false, surname: 'Nijhof'},
        {age: 14, balance: 70, firstName: 'Sander', gender: 'male', id: 72, present: false, surname: 'Snoek'},
    ],
        timestamp: 1557417600000
    },
    {
        location: 'Sporthal Oostenburg', players: [
        {age: 7, balance: -44, firstName: 'Joris', gender: 'male', id: 20, present: true, surname: 'Hoog'},
        {age: 16, balance: 96, firstName: 'Lars', gender: 'male', id: 21, present: true, surname: 'Overbeek'},
        {age: 9, balance: 50, firstName: 'Bas', gender: 'male', id: 32, present: false, surname: 'Maassen'},
        {age: 11, balance: 13, firstName: 'Bram', gender: 'male', id: 37, present: false, surname: 'Kock'},
        {age: 9, balance: 115, firstName: 'Kim', gender: 'female', id: 38, present: false, surname: 'Zandbergen'},
        {age: 9, balance: 60, firstName: 'Anouk', gender: 'female', id: 40, present: true, surname: 'Kooten'},
        {age: 9, balance: 189, firstName: 'Emma', gender: 'female', id: 47, present: true, surname: 'Bogaard'},
        {age: 10, balance: 75, firstName: 'Jolle', gender: 'female', id: 49, present: true, surname: 'Akkerman'},
        {age: 12, balance: 151, firstName: 'Eva', gender: 'female', id: 60, present: true, surname: 'Bogaard'},
        {age: 14, balance: 186, firstName: 'Tijmen', gender: 'male', id: 62, present: false, surname: 'Zandbergen'},
        {age: 15, balance: 28, firstName: 'Linde', gender: 'female', id: 64, present: false, surname: 'Broeders'},
        {age: 3, balance: 25, firstName: 'Faruk', gender: 'male', id: 70, present: true, surname: 'Verschuren'},
        {age: 8, balance: 34, firstName: 'Sander', gender: 'male', id: 71, present: false, surname: 'Kleef'},
        {age: 13, balance: 134, firstName: 'Marco', gender: 'male', id: 74, present: true, surname: 'Overbeek'},
    ],
        timestamp: 1557478800000
    },
    {
        location: 'Sporthallen Zuid', players: [
        {age: 14, balance: 98, firstName: 'Marielle', gender: 'female', id: 2, present: true, surname: 'Zuidema'},
        {age: 11, balance: 64, firstName: 'Martijn', gender: 'male', id: 5, present: true, surname: 'Cremers'},
        {age: 12, balance: 89, firstName: 'Justin', gender: 'male', id: 7, present: false, surname: 'Lier'},
        {age: 5, balance: 60, firstName: 'Fleur', gender: 'female', id: 10, present: false, surname: 'Bleeker'},
        {age: 14, balance: 169, firstName: 'Danille', gender: 'female', id: 36, present: false, surname: 'Wijnands'},
        {age: 12, balance: 183, firstName: 'Britt', gender: 'female', id: 44, present: true, surname: 'Delft'},
        {age: 14, balance: -39, firstName: 'Lorenzo', gender: 'male', id: 48, present: true, surname: 'Altena'},
        {age: 8, balance: 30, firstName: 'Julie', gender: 'female', id: 50, present: false, surname: 'Ooms'},
        {age: 8, balance: 177, firstName: 'Robin', gender: 'male', id: 57, present: true, surname: 'Koelewijn'},
        {age: 14, balance: -33, firstName: 'Oussama', gender: 'male', id: 65, present: true, surname: 'Klein'},
        {age: 13, balance: 84, firstName: 'Romy', gender: 'female', id: 73, present: true, surname: 'Wolff'},
        {age: 16, balance: -22, firstName: 'Romy', gender: 'female', id: 78, present: true, surname: 'Broeders'},
    ],
        timestamp: 1557493200000
    },
    {
        location: 'Sportcentrum Universum', players: [
        {age: 14, balance: 99, firstName: 'Isabel', gender: 'female', id: 4, present: false, surname: 'Verkerk'},
        {age: 5, balance: 131, firstName: 'Britt', gender: 'female', id: 14, present: false, surname: 'Wever'},
        {age: 13, balance: 153, firstName: 'Rosalie', gender: 'female', id: 23, present: true, surname: 'Klok'},
        {age: 4, balance: 104, firstName: 'Merijn', gender: 'male', id: 24, present: true, surname: 'Maanen'},
        {age: 14, balance: 162, firstName: 'Michael', gender: 'male', id: 27, present: false, surname: 'Zanden'},
        {age: 12, balance: 123, firstName: 'Julia', gender: 'female', id: 31, present: true, surname: 'Loos'},
        {age: 6, balance: 30, firstName: 'Natasha', gender: 'female', id: 46, present: false, surname: 'Krol'},
        {age: 3, balance: 83, firstName: 'Marcel', gender: 'male', id: 51, present: true, surname: 'Bloem'},
        {age: 10, balance: -10, firstName: 'Tijmen', gender: 'male', id: 55, present: false, surname: 'Claassen'},
        {age: 6, balance: 169, firstName: 'Faruk', gender: 'male', id: 56, present: true, surname: 'Verstappen'},
        {age: 16, balance: 141, firstName: 'Jimmy', gender: 'male', id: 58, present: true, surname: 'Olde'},
        {age: 8, balance: 95, firstName: 'Giovanni', gender: 'male', id: 61, present: false, surname: 'Westerhof'},
        {age: 6, balance: 39, firstName: 'Tessa', gender: 'female', id: 69, present: false, surname: 'Klein'},
    ],
        timestamp: 1557507600000
    },
];
